// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tietokantatesti.Migrations
{
    [DbContext(typeof(TietokantaContext))]
    [Migration("20211116202523_uuskentta")]
    partial class uuskentta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("tietue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PVM")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Tietueet");
                });
#pragma warning restore 612, 618
        }
    }
}
